### ISSUE TITLE
ETAPA 1 - REQUISITOS - Elaboração do documento da Entrega 1

### ISSUE THREAD

**Issue by mugubr** [mugubr/projeto-ceub#3]
Nesse card, discutiremos todas as questões relacionadas à elaboração e entrega do primeiro documento (Entrega 1).

**Documento:**
https://docs.google.com/document/d/1ps8z5yzavv29hgfFNnLxPjuoBoYCBxJ5t0nmkflyt0w/edit?usp=sharing

**Comment by Corravel** [comment]
**Esboço do documento:**
[https://docs.google.com/document/d/1Ww8GwkQj6rQ_1CQfQ5QpSN677qf_7LTTN_QtQ03Bgx4/edit](url)

**Comment by mugubr** [comment]
Aguardando feedback do professor.

**Comment by mugubr** [comment]
Documento terminado e entregue.
